# Generated by Django 4.2.18 on 2025-03-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='clash_of_clans_town_hall_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
