# Generated by Django 4.2.18 on 2025-03-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gameprofile_clash_of_clans_town_hall_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameprofile',
            old_name='call_of_duty_kd_ratio',
            new_name='brawl_star_trophies',
        ),
        migrations.RenameField(
            model_name='gameprofile',
            old_name='call_of_duty_username',
            new_name='brawl_star_username',
        ),
    ]
