# Generated by Django 4.2.18 on 2025-03-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_cod_username_gameprofile_cod_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='cod_kd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
